name: CI/CD for python Django app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python 3.x environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r /backend/requirements.txt

      # Run unit tests
      - name: Run tests
        run: |
          pytest tests/